apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-counter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-counter
  template:
    metadata:
      labels:
        app: word-counter
    spec:
      containers:
      - name: word-counter
        image: kyathavr/word-counter
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: word-counter-service
spec:
  selector:
    app: word-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30099
  type: NodePort
