FROM python:3.9-slim

WORKDIR /home/data

COPY IF.txt AlwaysRememberUsThisWay.txt /home/data/
COPY scripts.py /home/data/

# Create the output directory
RUN mkdir -p /home/data/output

# Install dependencies if needed
RUN pip install --no-cache-dir requests

CMD ["python", "scripts.py"]
